import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";
import brushCursor from "@/components/ui/Paint";
import Footer from "@/components/layouts/Footer/Footer";

// Existing Geist fonts
const font = IBM_Plex_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${font.className}  antialiased`}
        style={{ cursor: brushCursor }}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
